version: '3.9'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      sv-dkhp-network:
        ipv4_address: 172.20.0.10
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      sv-dkhp-network:
        ipv4_address: 172.20.0.11
  java:
    build: 
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sv_dkhp?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      sv-dkhp-network:
        ipv4_address: 172.20.0.12
  mysql:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sv_dkhp
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      sv-dkhp-network:
        ipv4_address: 172.20.0.13
      
networks:
  sv-dkhp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
volumes:
  mysql_data: