version: '3.9'
services:
  mysql:
    container_name: mysql
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sv_dkhp
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sv-dkhp-network
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - sv-dkhp-network
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - java
    networks:
      - sv-dkhp-network
  java:
    container_name: java
    build: 
      context: ./java
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sv_dkhp?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - sv-dkhp-network
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - web
      - java
    networks:
      - sv-dkhp-network
networks:
  sv-dkhp-network:
    driver: bridge
volumes:
  mysql_data: