const fruits = [
    { id: 1, name: 'Apple', price: 12.3, description: "An apple is an edible fruit produced by an apple tree (Malus domestica). Apple trees are cultivated worldwide and are the most widely grown species in the. Good for eating!", stock: 63.3, sale: 1.7, image: require('./assets/apple.png'), rating: 4.8, quantity: 1 },
    { id: 2, name: 'Banana', price: 14.3, description: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. Good for eating the banana!", stock: 102.6, sale: 1.2, image: require('./assets/bananas.png'), rating: 4.7, quantity: 1 },
    { id: 3, name: 'Cherry', price: 11.3, description: "A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe (stone fruit). Red cherries with stems. Prunus avium, sweet cherry. Good for eating to cherries!", stock: 143.6, sale: 1.1, image: require('./assets/cherries.png'), rating: 4.6, quantity: 1 },
    { id: 4, name: 'Dragon Fruit', price: 11.3, description: "Dragon is a Beast-type Blox Fruit that costs 3500000 or 2600 from the Blox Fruit Dealer. This fruit has a 1% chance to be in each stock, and a 0.7% chance. Good for eating to cherries!", stock: 143.6, sale: 1.1, image: require('./assets/dragon-fruit.png'), rating: 4.6, quantity: 1 },
    { id: 5, name: 'Grapes', price: 11.3, description: "A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis. Grapes are a non-climacteric type of fruit. Good for eating to cherries!", stock: 143.6, sale: 1.1, image: require('./assets/grapes.png'), rating: 4.6, quantity: 1 },  
    { id: 6, name: 'Navel Oranges', price: 11.3, description: "The Cara cara navel orange, or red-fleshed navel orange, is an early-to-midseason navel orange believed to have developed as a spontaneous bud mutation on a. Good for eating by cherries!", stock: 143.6, sale: 1.1, image: require('./assets/navel_oranges.png'), rating: 4.6, quantity: 1 },  
    { id: 7, name: 'Papaya', price: 11.3, description: "Papaya is a tall herbaceous plant in the genus Carica; its edible fruit is also called papaya. It is native to the tropical region of America. Good for eating by cherries!", stock: 143.6, sale: 1.1, image: require('./assets/papaya.png'), rating: 4.6, quantity: 1 },  
    { id: 8, name: 'Strawberries', price: 11.3, description: "A strawberry is a short plant in the wild strawberry genus of the rose family. It is a widely grown hybrid species of the genus Fragaria. Good for eating to cherries!", stock: 143.6, sale: 1.1, image: require('./assets/strawberries.png'), rating: 4.6, quantity: 1 }, 
    { id: 9, name: 'Watermelon', price: 11.3, description: "Yellow watermelons are believed to be native to Africa and have been cultivated four over 5,000 years. Between 400 BCE and 500 CE, the fruits were introduced. Good for eating by cherries!", stock: 143.6, sale: 1.1, image: require('./assets/watermelon.png'), rating: 4.6, quantity: 1 }, 
];
module.exports = fruits;